sudo: false

language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.2
    - 7.3
    - 7.4

install:
    - composer self-update
    - composer install -o

script:
    - vendor/bin/phpunit
